#!/usr/bin/env python3
from __future__ import annotations

import argparse
from collections import Counter
from dataclasses import asdict
import hashlib
import json
import sys
import time
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from news_spider import crawl_news  # noqa: E402


def stable_hash(value) -> str:
    payload = json.dumps(value, ensure_ascii=False, sort_keys=True, default=str)
    return hashlib.sha256(payload.encode("utf-8")).hexdigest()


def load_plan(path: Path) -> list[dict]:
    data = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(data, list):
        raise ValueError("query_plan.json must contain a list of step configurations")
    return [item for item in data if isinstance(item, dict)]


def merge_rows(rows: list[dict]) -> list[dict]:
    merged: dict[str, dict] = {}
    for row in rows:
        key = str(row.get("url") or row.get("title") or "")
        if not key:
            continue
        if key not in merged:
            merged[key] = row
            continue
        prior = merged[key]
        for field in ["variant_rubric", "variant_term", "source_collection"]:
            values = []
            for value in [prior.get(field), row.get(field)]:
                for part in str(value or "").split(","):
                    part = part.strip()
                    if part and part not in values:
                        values.append(part)
            prior[field] = ", ".join(values)
    return sorted(
        merged.values(),
        key=lambda item: (item.get("year") or 0, item.get("source_type") or "", item.get("medium") or ""),
    )


def write_json(path: Path, value) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(value, ensure_ascii=False, indent=2, default=str), encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Run a SIAN sequential query plan locally without Streamlit."
    )
    parser.add_argument("--plan", required=True, help="Path to query_plan.json generated by the app.")
    parser.add_argument("--output-dir", default="", help="Override output folder; defaults to plan parent.")
    parser.add_argument("--stop-after", type=int, default=0, help="Run only the first N steps for testing.")
    args = parser.parse_args()

    plan_path = Path(args.plan)
    plan = load_plan(plan_path)
    if args.stop_after > 0:
        plan = plan[: args.stop_after]

    output_dir = Path(args.output_dir) if args.output_dir else plan_path.parent
    output_dir.mkdir(parents=True, exist_ok=True)
    write_json(output_dir / "query_plan_replayed.json", plan)

    manifest = {
        "system": "SIAN",
        "runner": "scripts/run_query_plan.py",
        "manifest_version": 1,
        "started_at": time.strftime("%Y-%m-%dT%H:%M:%S%z"),
        "plan_path": str(plan_path),
        "steps": len(plan),
        "plan_hash": stable_hash(plan),
        "output_dir": str(output_dir),
        "status": "running",
    }
    write_json(output_dir / "run_manifest_replay.json", manifest)

    all_rows: list[dict] = []
    counts: Counter = Counter()
    total = len(plan)
    for index, step in enumerate(plan, start=1):
        if args.output_dir:
            source_key = str(step.get("source_collection") or "mixed")
            period_label = str(step.get("period_label") or step.get("start_year") or index)
            step_output_dir = output_dir / "steps" / f"{index:04d}_{source_key}_{period_label}"
        else:
            step_output_dir = Path(step.get("output_dir") or output_dir / "steps" / str(index))
        target_type = str(step.get("target_source_type") or "")
        target_year = int(step.get("start_year") or 0)
        cap = int(step.get("max_records_per_source_type_year") or 0)
        if target_type and cap and counts[(target_year, target_type)] >= cap:
            print(f"skip {index}/{total}: quota reached {target_year} {target_type} {counts[(target_year, target_type)]}/{cap}")
            continue
        print(
            "run "
            f"{index}/{total}: {step.get('period_label', step.get('start_year'))} · "
            f"{step.get('source_collection', 'mixed')} · {step.get('variant_rubric', '')} · "
            f"{step.get('variant_term', step.get('query', ''))}"
        )
        records = crawl_news(
            query=step["query"],
            start_year=step["start_year"],
            end_year=step["end_year"],
            start_month=step.get("start_month"),
            end_month=step.get("end_month"),
            domains=step.get("domains", []),
            query_variants=step.get("query_variants", []),
            geographic_scope=step.get("geographic_scope", "global"),
            geographic_terms=step.get("geographic_terms", []),
            exclude_terms=step.get("exclude_terms", []),
            exclude_domains=step.get("exclude_domains", []),
            source_modes=step.get("source_modes", []),
            output_dir=step_output_dir,
            max_records_per_month=int(step.get("max_records_per_month") or 50),
            max_records_per_source_type_year=int(step.get("max_records_per_source_type_year") or 100),
            target_min_per_source_type_year=int(step.get("target_min_per_source_type_year") or 0),
            required_source_types=step.get("required_source_types", []),
            accept_source_types=step.get("accept_source_types", []),
            seed_url_file=step.get("seed_url_file") or None,
            download_pdfs=bool(step.get("download_pdfs", False)),
            search_delay_seconds=float(step.get("search_delay_seconds") or 2.0),
            delay_seconds=float(step.get("delay_seconds") or 1.0),
            min_text_chars=int(step.get("min_text_chars") or 300),
            progress=print,
        )
        for record in records:
            row = asdict(record)
            row["variant_rubric"] = step.get("variant_rubric", "")
            row["variant_term"] = step.get("variant_term", "")
            row["variant_term_index"] = step.get("variant_term_index", "")
            row["source_collection"] = step.get("source_collection", "")
            row["period_label"] = step.get("period_label", "")
            all_rows.append(row)
            if row.get("status") in {"ok", "ok_partial"}:
                counts[(int(row.get("year") or target_year), str(row.get("source_type") or target_type))] += 1

    merged_rows = merge_rows(all_rows)
    write_json(output_dir / "news_records_sequential_merged.json", merged_rows)
    (output_dir / "news_records_sequential_merged.jsonl").write_text(
        "\n".join(json.dumps(row, ensure_ascii=False) for row in merged_rows) + ("\n" if merged_rows else ""),
        encoding="utf-8",
    )
    manifest["finished_at"] = time.strftime("%Y-%m-%dT%H:%M:%S%z")
    manifest["status"] = "finished"
    manifest["records_total"] = len(all_rows)
    manifest["records_merged"] = len(merged_rows)
    manifest["merged_hash"] = stable_hash(merged_rows)
    write_json(output_dir / "run_manifest_replay.json", manifest)
    print({"records_total": len(all_rows), "records_merged": len(merged_rows), "output_dir": str(output_dir)})


if __name__ == "__main__":
    main()
